### ISSUE TITLE
[介面] 退款 popup 右上角x 無法關閉視窗 

### ISSUE THREAD

**Issue by ppuff1988** [DaydreamLab/dingsomething-issues#22]
## 問題描述

要輸入退款金額 跟 不用輸入退款金額的介面都不能關閉視窗，一定要點放棄
## 螢幕截圖

![螢幕快照 2019-10-07 上午11 22 43](https://user-images.githubusercontent.com/2792565/66284145-1b0f5080-e8f9-11e9-97d4-d1a4487b8c95.png)
![螢幕快照 2019-10-07 上午11 52 09](https://user-images.githubusercontent.com/2792565/66284147-1d71aa80-e8f9-11e9-94a5-adcfbb16dbfd.png)

**Comment by littlegreening** [comment]
你的意思是點了確定按鈕也無法關閉視窗嗎？

**Comment by ppuff1988** [comment]
> 你的意思是點了確定按鈕也無法關閉視窗嗎？
點確定沒有問題
> 你預期的是點了右上角的叉叉圖示要關閉視窗嗎？（等同於點即放棄按鈕）
對

**Comment by littlegreening** [comment]
已與 #20 一起處理
