### ISSUE TITLE
[後台/商家設定] 上一次儲存的商家介紹&聯繫email無法在後台查看

### ISSUE THREAD

**Issue by cocowuu** [DaydreamLab/dingsomething-issues#28]
## 問題描述
商家設定的商家介紹＆聯繫email儲存後再度回到該功能，輸入框內原本的文字不見
## 重現方法
 
商家設定＞輸入商家介紹＞儲存＞跳至任一大功能＞回商家設定＞輸入框內原本的文字不見

## 預期結果
看到上一次儲存的商家介紹與email

**Comment by littlegreening** [comment]
後端 /api/admin/merchant 無傳 Email 以及商家介紹之內容

**Comment by ppuff1988** [comment]
done
